# Generated by Django 3.1.7 on 2021-03-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210322_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
